In [1]:
import pandas as pd

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [37]:
df.head(8)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   
5  MSI Crosshair 17 C12VF-264XES Intel Core i7-12...    New     MSI   
6  Lenovo Thinkpad E14 Gen 4 AMD Ryzen 5 5625U/8G...    New  Lenovo   
7  ASUS VivoBook 15 F515JA-EJ2882W Intel Core i7-...    New    Asus   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   
5   Crosshair  Intel Core i7   32     1000          SSD  RTX 4060    17.3   
6    ThinkPad    AMD Ryzen 5    8      256          SSD       NaN    14.0   
7    VivoBook  Intel Core i7    8      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01  
5    No      1699.00  
6    No       909.00  
7    No       809.01

In [38]:
df['Brand'].nunique()

27

In [39]:
total_records = len(df)
print(total_records)


2160


In [40]:
missing_columns = df.isnull().any().sum()
print(missing_columns)


3


In [41]:
median_screen = df['Screen'].median()
print(median_screen)


15.6


In [42]:
most_frequent = df['Screen'].mode()[0]
print(most_frequent)

15.6


In [44]:
df['Screen'] = df['Screen'].fillna(most_frequent)

In [45]:
most_frequent = df['Screen'].mode()
print(most_frequent)

0    15.6
Name: Screen, dtype: float64


In [47]:
innjoo_laptops = df[df['Brand'] == 'Innjoo']
print(innjoo_laptops)

                                                 Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128 

In [48]:
selected_columns = df[['RAM', 'Storage', 'Screen']]
print(selected_columns)

      RAM  Storage  Screen
0       8      512    15.6
1       8      256    15.6
2       8      256    15.6
3      16     1000    15.6
4      16      512    15.6
...   ...      ...     ...
2155   16     1000    17.3
2156   16     1000    17.3
2157   32     1000    17.3
2158   16     1000    13.4
2159   16      256    13.4

[2160 rows x 3 columns]


In [49]:
X = df[['RAM', 'Storage', 'Screen']].values
print(X)

[[   8.   512.    15.6]
 [   8.   256.    15.6]
 [   8.   256.    15.6]
 ...
 [  32.  1000.    17.3]
 [  16.  1000.    13.4]
 [  16.   256.    13.4]]


In [50]:
np.arrange(10)

NameError: name 'np' is not defined