In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.6)

array([2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6])

In [5]:
a = np.array([1,2,3,4,5,9,7])

In [6]:
a

array([1, 2, 3, 4, 5, 9, 7])

In [7]:
a.arange

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [8]:
np.arange(34)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [9]:
np.arange(2,36)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [10]:
np.zeros(5, 2)

TypeError: Cannot interpret '2' as a data type

In [11]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [13]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
n[0]

array([1, 2, 3])

In [15]:
n[0, 3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [16]:
n[0, 2]

np.int64(3)

In [17]:
n[0, 2] = 99

In [18]:
n

array([[ 1,  2, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [19]:
n[:, 2]

array([99,  6,  9])

In [20]:
n[:, 2] = [55,55,56]

In [21]:
n

array([[ 1,  2, 55],
       [ 4,  5, 55],
       [ 7,  8, 56]])

In [27]:
np.random.seed(2)
np.random.rand(5, 2) * 100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [1]:
np.zeros(4)

NameError: name 'np' is not defined